# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build Vue

on:
  push:
    branches: [ Desenvolvimento ]
  pull_request:
    branches: [ Desenvolvimento ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref }}
    - name: configure repo
      run:  |
        git config --global user.name 'Omnis-Builder'
        git config --global user.email 'Omnis-Actions@users.noreply.github.com'
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Cleaning Instalation
      run: npm ci
      working-directory: ./frontend
    - name: Install Dependencies
      run: npm install
      working-directory: ./frontend
    - name: Deploy
      run: npm run build        
      working-directory: ./frontend
    - name: Commit report
      run: |
        git add .
        git commit -m "[build]"
        git push
    
